config/routes.rb
Rails.application.routes.draw do
  resources :last_episodes

  delete 'last_episodes/:id', to: 'last_episodes#destroy', as: "delete_epi"
  resources :last_episodes do
    resources :comments
  end
  get "last_episodes/new", to: "last_episodes#new"
  get "last_episodes/index", to: "last_episodes#index"
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy', as: 'destroy_user_session_via_get'
  end
  root "last_episodes#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :last_episode
end

app/models/last_episode.rb
class LastEpisode < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord

has_many :comments, dependent: :destroy
has_many :last_episodes, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_action :verify_authenticity_token
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def new
    @comment = Comment.new
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def create
    param = comment_params.merge({ last_episode_id: params[:last_episode_id], user_id: current_user.id})
    @comment = Comment.new(param)
    # @comment.user = current_user
    puts true if @comment.save

    redirect_to  last_episode_path(LastEpisode.find(params[:last_episode_id]))
  end

  def edit

  end

  private 

  def comment_params
    params.require(:comment).permit(:content, :last_episode_id)
  end

 
    
end

app/controllers/last_episodes_controller.rb
class LastEpisodesController < ApplicationController
  before_action :authenticate_user!
  # before_action :check_id, only: [:index]
  
  def index
    @last_episodes = current_user.last_episodes
  end

  def new
    @last_episode = LastEpisode.new
  end

  def show
    @last_episode = LastEpisode.find(params[:id])
    @comment=Comment.new
 
  end

  def create
    @last_episode = LastEpisode.create(last_episode_params) 
    @last_episode.user_id = current_user.id
    @last_episode.save
    redirect_to @last_episode
  end

  def edit
    @last_episode = LastEpisode.find(params[:id])
  end

  def update
    @last_episode = LastEpisode.find(params[:id])
    @last_episode.update(params.require(:last_episode).permit(:episode_number, :name))
      
    redirect_to @last_episode
  end

  def destroy
    @last_episode = LastEpisode.find(params[:id]).destroy
    if @last_episode.present?
      @last_episode.destroy
    end
    redirect_to last_episodes
  end

  private

  def last_episode_params
    params.require(:last_episode).permit( :episode_number, :name, :comment_id)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/last_episodes_helper.rb
module LastEpisodesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: @comment, local: true, url: last_episode_comments_path) do |form| %>

    
  <div class="field container-fluid mt-2">
    <div class="row cardBody py-5 mt-5">
      <div class="col-lg-4 py-2">
        <div class="card-body bg-dark">

  <div class="field text-info">
    <%= form.label :content %>
    <%= form.text_area :content, class:"forminput"%>
  </div>

  <div class="actions text-info btn btn-primary bg-dark">
    <%= form.submit %>
     </div>
   </div>
     </div>
      </div>

    
<% end %>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/vie/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index..erb</p>

app/views/comments/new.html.erb
<%= render 'form'%>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/last_episodes/_form.html.erb
<%= form_with(model: @last_episode, local: true) do |form| %>
  <% if @last_episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@last_episode.errors.count, "error") %> prohibited this @last_episode from being saved:</h2>

      <ul>
        <% @last_episode.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    

  <div class="field container mt-5 text-info ">
    <div class="row cardBody py-5 mt-5">
      <div class="col-lg-3 col-md-6 py-2 w-75 p-3">
        <div class="card-body bg-dark ">
          
    <%= form.label :name %>
    <%= form.text_field :name %>



    <%= form.label :episode_number %>
    <%= form.text_field :episode_number %>
 

  <div class="actions btn btn-primary bg-dark text-info">
    <%= form.submit %>
    </div>
 </div>
   </div>
     </div>
      </div>


    
<% end %>

app/views/last_episodes/edit.html.erb
<h1>LastEpisodes#edit</h1>
<h1><%= current_user.email %>'s Last Episodes</h1>


<%= render 'form' %>

app/views/last_episodes/index.html.erb
  <!-- Page Content -->
  <div class="container mt-5">
   
         


    <!-- Marketing Icons Section -->
    <div class="row cardBody py-5 mt-5">
      <% @last_episodes.each do |lastEpisode| %>
      <div class="col-lg-3 col-md-6 py-2">
        <div class="card-body bg-dark">
          <h4 class=" text-primary card-title mb-1"><%= link_to lastEpisode.name, last_episode_path(lastEpisode) %></h4>
          
            <p class="card-text mb-1"><%= link_to lastEpisode.episode_number, last_episode_path(lastEpisode) %></p>
          </div>
          <div class="card-footer">
            <p class="btn btn-primary bg-dark"><%= link_to 'Edit', edit_last_episode_path(lastEpisode) %></p>
            <p class="btn btn-primary bg-dark"><%= link_to 'Add Comment', new_last_episode_comment_path(lastEpisode)  %></p>
          </div>
        
      </div>
      <% end %>

app/views/last_episodes/new.html.erb
<%= render 'form' %>

app/views/last_episodes/show.html.erb
  <div class="container mt-5">
  <h4 class="text-info card-title mb-1"> Series Name : <%= @last_episode.name%></h4>


<div class="row cardBody py-5 mt-5">
   <div class="col-lg-3 col-md-6 py-2">
    <div class="card-body bg-dark">

  <ul>
    <h4 class="text-info card-text "> Episode Number : <%= @last_episode.episode_number%></h4>

    <h2 class= "text-info card-title mb-1" >Comments  </h2>
    <% @last_episode.comments.each do |c|%>
   <li class="text-info" ><p> <%=c.content%></p></li>
    <%end%>
            <p class="btn btn-primary bg-dark"> <%= link_to 'Delete Serie', delete_epi_path(@last_episode), method: :delete, data: {confirm: 'Are you sure?'} %></p>
            <p class="btn btn-primary bg-dark"><%= link_to 'Add Comment',  new_last_episode_comment_path(@last_episode) %></p>
</ul>
</div>
   </div>
    </div>
</div>



   
         

app/views/layouts/_nav.html.erb
 <nav class="navbar navbar-dark bg-dark">
  <!-- Navbar content -->

 <p class="navbar-text pull-right">
  <h4><%= link_to 'Home', last_episodes_path, :class => 'navbar-link' %></h4>
  <h4><%= link_to 'New Series', new_last_episode_path%></h4>
  <% if user_signed_in? %><p class="text-primary">
    Logged in as <strong><%= current_user.email %></strong>.</p>
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
  </p>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  </nav>

  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tv Tracker App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="stylesheets/bootstrap.min.scss" rel="style">
   
   <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
  
  <%= render 'layouts/nav'%>


<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag("madMen.jpg",  class:"d-block img-d",size: "400x640", alt:"Second slide",) %>
    </div>
    <div class="carousel-item">
      <%= image_tag("got.jpg", class:" d-block img-d",size: "400x640", alt:"First slide") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("rickAndMorty.png",  class:"d-block img-d",size: "400x640", alt:"Second slide") %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>








    <%= yield %>
    
  <footer class="footer navbar-fixed-bottom">
      <div class="container text-center">
     
       <span class="text-muted ">
       Copyright &copy; Abdulrahman Alisulami 2019. &nbsp Number of Users: &nbsp <%=User.count %> 
        </span>      
     </div>
    </footer>

      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  
  </body>
</html>

app/views/pages/home.html.erb
<h1>Heloooooo</h1>
<p>Find me in app/views/pages/home.html.erb</p>